# Generated by Django 4.1.4 on 2022-12-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0002_agent_profile_picture_lead_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='special_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='special_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='stock',
            name='special_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='worker',
            name='special_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
